### ISSUE TITLE
White text on the control input

### ISSUE THREAD

**Issue by prawnsalad** [irccom/mobileapp#2]
```
[22:44:33]  <prawnsalad>	so yea, do you have dark mode enabled or something
[22:44:36]  <prawnsalad>	in ios
[22:44:50]  <eskimo>	yeah, dark mode on iOS 13
```

![image](https://user-images.githubusercontent.com/725880/66687009-2b1c8c80-ec79-11e9-89f8-9d8aa0b4d33e.png)

**Comment by tralves** [comment]
Fixed, and the text will now be black. It will be available on the next release.

Support for dark mode will be available when we implement the dark theme. Then, we will set the default theme according to the iOS config (light/dark mode).

**Comment by eskimo** [comment]
I would recommend having that be an option that can be disabled. Some people will prefer to always use dark or light independent of the system setting.

**Comment by tralves** [comment]
That's the plan. The system setting will only define the default (first) theme :)
