### ISSUE TITLE
Force close exception

### ISSUE THREAD

**Issue by MrGrays** [irccom/mobileapp#3]
Hello

I am currently unable to test this application due to the application automatically closing when I attempt to join a channel. My device is a Samsung S10 Plus

**Comment by tralves** [comment]
Hi!

I can see the crash report but need more info. How are you joining the channel? There are several ways to join a channel:

- `/join #channel`;
- In the "Join Channel" screen;
- tapping "Rejoin #channel"...

**Comment by MrGrays** [comment]
In the "Join Channel" screen;

**Comment by tralves** [comment]
It was fixed in another related issue. The update will be released later today.

If you could confirm the fix after you get the update, that would be 💯 .

Thanks!

**Comment by MrGrays** [comment]
Working perfect since latest update
